# Setup
title:               You&
tagline:             'Data_Science & Life'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://lanyon.getpoole.com
baseurl:             ''
paginate:            5
permalink:           pretty
category_dir: category/
tag_dir: tag/


# About/contact
author:
  name:              TaeHwan Youn
  url:               https://twitter.com/mdo
  email:             youn4576@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
